@startuml

title __ABSTRACT_'s Class Diagram__\n

  namespace factory.examples.abstract_ {
    class factory.examples.abstract_.AbstractFactoryDemo {
        {static} + main()
    }
  }
  

  namespace factory.examples.abstract_ {
    class factory.examples.abstract_.Coffee {
        + consume()
    }
  }
  

  namespace factory.examples.abstract_ {
    class factory.examples.abstract_.CoffeeFactory {
        + prepare()
    }
  }
  

  namespace factory.examples.abstract_ {
    class factory.examples.abstract_.HotDrinkMachine {
        - namedFactories : List<Pair<String, IHotDrinkFactory>>
        + HotDrinkMachine()
        + makeDrink()
    }
  }
  

  namespace factory.examples.abstract_ {
    interface factory.examples.abstract_.IHotDrink {
        {abstract} + consume()
    }
  }
  

  namespace factory.examples.abstract_ {
    interface factory.examples.abstract_.IHotDrinkFactory {
        {abstract} + prepare()
    }
  }
  

  namespace factory.examples.abstract_ {
    class factory.examples.abstract_.Tea {
        + consume()
    }
  }
  

  namespace factory.examples.abstract_ {
    class factory.examples.abstract_.TeaFactory {
        + prepare()
    }
  }
  

  factory.examples.abstract_.Coffee .up.|> factory.examples.abstract_.IHotDrink
  factory.examples.abstract_.CoffeeFactory .up.|> factory.examples.abstract_.IHotDrinkFactory
  factory.examples.abstract_.Tea .up.|> factory.examples.abstract_.IHotDrink
  factory.examples.abstract_.TeaFactory .up.|> factory.examples.abstract_.IHotDrinkFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
