@startuml

title __STRING's Class Diagram__\n

  namespace decorator.string {
    class decorator.string.DecoratorStringDemo {
        {static} + main()
    }
  }
  

  namespace decorator.string {
    class decorator.string.MagicString {
        - string : String
        + MagicString()
        + charAt()
        + chars()
        + codePointAt()
        + codePointBefore()
        + codePointCount()
        + codePoints()
        + compareTo()
        + compareToIgnoreCase()
        + concat()
        + contains()
        + contentEquals()
        + contentEquals()
        {static} + copyValueOf()
        {static} + copyValueOf()
        + endsWith()
        + equalsIgnoreCase()
        {static} + format()
        {static} + format()
        + getBytes()
        + getBytes()
        + getBytes()
        + getBytes()
        + getChars()
        + getNumberOfVowels()
        + indexOf()
        + indexOf()
        + indexOf()
        + indexOf()
        + isEmpty()
        {static} + join()
        {static} + join()
        + lastIndexOf()
        + lastIndexOf()
        + lastIndexOf()
        + lastIndexOf()
        + length()
        + matches()
        + offsetByCodePoints()
        + regionMatches()
        + regionMatches()
        + replace()
        + replace()
        + replaceAll()
        + replaceFirst()
        + split()
        + split()
        + startsWith()
        + startsWith()
        + subSequence()
        + substring()
        + substring()
        + toCharArray()
        + toLowerCase()
        + toLowerCase()
        + toString()
        + toUpperCase()
        + toUpperCase()
        + trim()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
        {static} + valueOf()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
